# 05 Inspect an Eelbrain TRF Pickle

This notebook opens one trusted local Eelbrain `BoostingResult` pickle and inventories its attributes without printing large arrays by default. It shows both public data attributes (including properties) and the internal fields actually stored in the pickled object.

> Only unpickle files that you created locally or obtained from a trusted source. Python pickle files can execute code while loading.

In [1]:
from pathlib import Path
import inspect
import json
import sys

import numpy as np
import pandas as pd
from IPython.display import display
from eelbrain import NDVar, load


def find_pipeline_dir(start=Path.cwd()):
    start = Path(start).resolve()
    candidates = [start, *start.parents, start / 'analysis' / 'trf_pipeline']
    for path in candidates:
        if (path / 'alice_eelbrain_main_experiment.py').exists():
            return path
    raise FileNotFoundError(f'Could not find alice_eelbrain_main_experiment.py from {start}')


PIPELINE_DIR = find_pipeline_dir()
if str(PIPELINE_DIR) not in sys.path:
    sys.path.insert(0, str(PIPELINE_DIR))

from alice_eelbrain_main_experiment import TRF_OPTIONS, alice

SUBJECT = '01'
MODEL = 'gammatone-8'
STATE = {'raw': '0.5-20', 'epoch': 'chapter-1', 'inv': ''}

PICKLE_PATH = Path(
    alice.load_trf(MODEL, subject=SUBJECT, path_only=True, **STATE, **TRF_OPTIONS)
)
MANIFEST_PATH = PICKLE_PATH.with_name(PICKLE_PATH.name + '.manifest.json')

print(f'Subject: sub-{SUBJECT}')
print(f'Pickle: {PICKLE_PATH}')
print(f'Pickle exists: {PICKLE_PATH.exists()}')
print(f'Manifest: {MANIFEST_PATH}')
print(f'Manifest exists: {MANIFEST_PATH.exists()}')

INFO    :  *** AliceComprehensionEelbrainMain initialized with root /Users/yanyuwoo/Data/bids on 2026-07-20 21:19:23 ***
INFO    :  Using eelbrain 0.43.0a1, mne 1.11.0.
Subject: sub-01
Pickle: /Users/yanyuwoo/Data/bids/derivatives/eelbrain/cache/trf/sub-01/subject-01_raw-0.5-20_epoch-chapter-1_key-e022d094f8f36fbb.pickle
Pickle exists: True
Manifest: /Users/yanyuwoo/Data/bids/derivatives/eelbrain/cache/trf/sub-01/subject-01_raw-0.5-20_epoch-chapter-1_key-e022d094f8f36fbb.pickle.manifest.json
Manifest exists: True

In [2]:
if not PICKLE_PATH.exists():
    raise FileNotFoundError(
        f'{PICKLE_PATH} does not exist. Run the single-subject or batch TRF notebook first.'
    )

result = load.unpickle(PICKLE_PATH)

print('Python type:', type(result))
print('Result:', result)
print('Stored field count:', len(vars(result)))

Python type: <class 'eelbrain._trf._boosting.BoostingResult'>
Result: <BoostingResult eeg ~ gammatone-8, -0.1 - 1, error=l1, basis=0.05, partitions=5, test=1, selective_stopping=1>
Stored field count: 37

## Attribute inventory

Large `NDVar` and NumPy values are summarized by dimensions, shape, dtype, finite-value count, and basic statistics. The full object remains available through `result` and the `show_attribute()` helper below.

In [3]:
def compact_repr(value, limit=240):
    text = repr(value).replace('\n', ' ')
    return text if len(text) <= limit else text[: limit - 3] + '...'


def array_statistics(array):
    array = np.asarray(array)
    out = {
        'shape': str(array.shape),
        'dtype': str(array.dtype),
        'finite': '',
        'min': '',
        'max': '',
        'mean': '',
    }
    if np.issubdtype(array.dtype, np.number):
        finite = np.isfinite(array)
        out['finite'] = f'{int(finite.sum())}/{array.size}'
        if finite.any():
            values = array[finite]
            out['min'] = float(values.min())
            out['max'] = float(values.max())
            out['mean'] = float(values.mean())
    return out


def summarize_value(name, value, source):
    row = {
        'name': name,
        'source': source,
        'python_type': f'{type(value).__module__}.{type(value).__qualname__}',
        'summary': compact_repr(value),
        'dimensions': '',
        'shape': '',
        'dtype': '',
        'finite': '',
        'min': '',
        'max': '',
        'mean': '',
        'error': '',
    }
    if isinstance(value, NDVar):
        row['dimensions'] = ', '.join(repr(dim) for dim in value.dims)
        row.update(array_statistics(value.x))
    elif isinstance(value, np.ndarray):
        row.update(array_statistics(value))
    return row


def inventory_public_attributes(obj):
    rows = []
    callable_rows = []
    for name in sorted(name for name in dir(obj) if not name.startswith('_')):
        try:
            value = getattr(obj, name)
        except Exception as exc:
            row = summarize_value(name, None, 'public attribute/property')
            row['error'] = repr(exc)
            rows.append(row)
            continue
        if callable(value):
            try:
                signature = str(inspect.signature(value))
            except (TypeError, ValueError):
                signature = '(signature unavailable)'
            callable_rows.append({'name': name, 'signature': signature})
        else:
            rows.append(summarize_value(name, value, 'public attribute/property'))
    return pd.DataFrame(rows), pd.DataFrame(callable_rows)


def inventory_stored_fields(obj):
    return pd.DataFrame(
        summarize_value(name, value, 'stored in pickle')
        for name, value in sorted(vars(obj).items())
    )


# Capture stored fields first: evaluating some public properties can cache
# derived values on the in-memory object that were not present in the pickle.
stored_fields = inventory_stored_fields(result)
public_attributes, public_methods = inventory_public_attributes(result)

In [4]:
print(f'Public data attributes/properties: {len(public_attributes)}')
display(public_attributes)

print(f'Internal fields stored in pickle: {len(stored_fields)}')
display(stored_fields)

print(f'Public callable methods (listed separately): {len(public_methods)}')
display(public_methods)

Public data attributes/properties: 39

,name,source,python_type,summary,dimensions,shape,dtype,finite,min,max,mean,error
0,algorithm_version,public attribute/property,builtins.int,3,,,,,,,,
1,basis,public attribute/property,builtins.float,0.05,,,,,,,,
2,basis_window,public attribute/property,builtins.str,'hamming',,,,,,,,
3,delta,public attribute/property,builtins.float,0.005,,,,,,,,
4,error,public attribute/property,builtins.str,'l1',,,,,,,,
5,execution_context,public attribute/property,builtins.dict,"{'machine': 'arm64', 'architecture': ('64bit',...",,,,,,,,
6,fit,public attribute/property,builtins.NoneType,None,,,,,,,,
7,h,public attribute/property,eelbrain._data_obj.NDVar,"<NDVar 'gammatone-8': 60 sensor, 8 frequency, ...","<Sensor n=60, name=None>, Scalar('frequency', ...","(60, 8, 56)",float64,26880/26880,-0.010625,0.01575,-0.000013,
8,h_scaled,public attribute/property,eelbrain._data_obj.NDVar,"<NDVar 'gammatone-8': 60 sensor, 8 frequency, ...","<Sensor n=60, name=None>, Scalar('frequency', ...","(60, 8, 56)",float64,26880/26880,-0.0,0.0,-0.0,
9,h_source,public attribute/property,eelbrain._data_obj.NDVar,"<NDVar 'gammatone-8': 60 sensor, 8 frequency, ...","<Sensor n=60, name=None>, Scalar('frequency', ...","(60, 8, 55)",float64,26400/26400,-0.01775,0.01725,-0.000013,
10,h_time,public attribute/property,eelbrain._data_obj.UTS,"UTS(-0.1, 0.02, 56)",,,,,,,,
11,i_test,public attribute/property,builtins.NoneType,None,,,,,,,,
12,l1_residual,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'L1 residuals': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,36588.190111,36817.778781,36731.263819,
13,l1_total,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'L1 total': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,36784.0,36784.0,36784.0,
14,l2_residual,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'L2 residuals': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,61646.069876,129880.460315,73438.968227,
15,l2_total,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'L2 total': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,61797.697282,129844.291419,73550.704204,
16,mindelta,public attribute/property,builtins.NoneType,None,,,,,,,,
17,n_samples,public attribute/property,builtins.int,36784,,,,,,,,
18,partition_results,public attribute/property,builtins.NoneType,None,,,,,,,,
19,partitions,public attribute/property,builtins.int,5,,,,,,,,
20,proportion_explained,public attribute/property,eelbrain._data_obj.NDVar,<NDVar '1': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.000918,0.005323,0.001434,
21,r,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'Correlation': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.044885,0.092227,0.03268,
22,r_l1,public attribute/property,builtins.NoneType,None,,,,,,,,
23,r_rank,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'Rank correlation': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.033056,0.097646,0.043484,
24,residual,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'L1 residuals': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,36588.190111,36817.778781,36731.263819,
25,scale_data,public attribute/property,builtins.bool,True,,,,,,,,
26,selective_stopping,public attribute/property,builtins.int,1,,,,,,,,
27,splits,public attribute/property,eelbrain._trf.shared.Splits,<Splits: continuous data split into 5 sections...,,,,,,,,
28,t_run,public attribute/property,builtins.float,31.366239070892334,,,,,,,,
29,tstart,public attribute/property,builtins.float,-0.1,,,,,,,,
30,tstop,public attribute/property,builtins.float,1.0,,,,,,,,
31,version,public attribute/property,builtins.int,15,,,,,,,,
32,x,public attribute/property,builtins.str,'gammatone-8',,,,,,,,
33,x_mean,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'gammatone-8': 8 frequency>,"Scalar('frequency', [165.2, ..., 11707.1] (8),...","(8,)",float64,8/8,0.065006,0.242697,0.149575,
34,x_scale,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'gammatone-8': 8 frequency>,"Scalar('frequency', [165.2, ..., 11707.1] (8),...","(8,)",float64,8/8,8.069925,24.034203,15.75865,
35,y,public attribute/property,builtins.str,'eeg',,,,,,,,
36,y_mean,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'eeg': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.000001,0.0,0.0,
37,y_pred,public attribute/property,builtins.NoneType,None,,,,,,,,
38,y_scale,public attribute/property,eelbrain._data_obj.NDVar,<NDVar 'eeg': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,0.000003,0.000201,0.000019,

Internal fields stored in pickle: 37

,name,source,python_type,summary,dimensions,shape,dtype,finite,min,max,mean,error
0,_h,stored in pickle,eelbrain._data_obj.NDVar,"<NDVar 'gammatone-8': 60 sensor, 8 frequency, ...","<Sensor n=60, name=None>, Scalar('frequency', ...","(60, 8, 55)",float64,26400/26400,-0.01775,0.01725,-0.000013,
1,_isnan,stored in pickle,numpy.ndarray,"array([False, False, False, False, False, Fals...",,"(60,)",bool,,,,,
2,_y_dims,stored in pickle,builtins.tuple,"(<Sensor n=60, name=None>,)",,,,,,,,
3,_y_info,stored in pickle,builtins.dict,"{'unit': 'V', 'meas': 'V', 'cmap': 'xpolar'}",,,,,,,,
4,algorithm_version,stored in pickle,builtins.int,3,,,,,,,,
5,basis,stored in pickle,builtins.float,0.05,,,,,,,,
6,basis_window,stored in pickle,builtins.str,'hamming',,,,,,,,
7,delta,stored in pickle,builtins.float,0.005,,,,,,,,
8,error,stored in pickle,builtins.str,'l1',,,,,,,,
9,execution_context,stored in pickle,builtins.dict,"{'machine': 'arm64', 'architecture': ('64bit',...",,,,,,,,
10,fit,stored in pickle,builtins.NoneType,None,,,,,,,,
11,i_test,stored in pickle,builtins.NoneType,None,,,,,,,,
12,l1_residual,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'L1 residuals': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,36588.190111,36817.778781,36731.263819,
13,l1_total,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'L1 total': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,36784.0,36784.0,36784.0,
14,l2_residual,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'L2 residuals': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,61646.069876,129880.460315,73438.968227,
15,l2_total,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'L2 total': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,61797.697282,129844.291419,73550.704204,
16,mindelta,stored in pickle,builtins.NoneType,None,,,,,,,,
17,n_samples,stored in pickle,builtins.int,36784,,,,,,,,
18,partition_results,stored in pickle,builtins.NoneType,None,,,,,,,,
19,partitions,stored in pickle,builtins.int,5,,,,,,,,
20,r,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'Correlation': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.044885,0.092227,0.03268,
21,r_l1,stored in pickle,builtins.NoneType,None,,,,,,,,
22,r_rank,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'Rank correlation': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.033056,0.097646,0.043484,
23,scale_data,stored in pickle,builtins.bool,True,,,,,,,,
24,selective_stopping,stored in pickle,builtins.int,1,,,,,,,,
25,splits,stored in pickle,eelbrain._trf.shared.Splits,<Splits: continuous data split into 5 sections...,,,,,,,,
26,t_run,stored in pickle,builtins.float,31.366239070892334,,,,,,,,
27,tstart,stored in pickle,builtins.float,-0.1,,,,,,,,
28,tstop,stored in pickle,builtins.float,1.0,,,,,,,,
29,version,stored in pickle,builtins.int,15,,,,,,,,
30,x,stored in pickle,builtins.str,'gammatone-8',,,,,,,,
31,x_mean,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'gammatone-8': 8 frequency>,"Scalar('frequency', [165.2, ..., 11707.1] (8),...","(8,)",float64,8/8,0.065006,0.242697,0.149575,
32,x_scale,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'gammatone-8': 8 frequency>,"Scalar('frequency', [165.2, ..., 11707.1] (8),...","(8,)",float64,8/8,8.069925,24.034203,15.75865,
33,y,stored in pickle,builtins.str,'eeg',,,,,,,,
34,y_mean,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'eeg': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.000001,0.0,0.0,
35,y_pred,stored in pickle,builtins.NoneType,None,,,,,,,,
36,y_scale,stored in pickle,eelbrain._data_obj.NDVar,<NDVar 'eeg': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,0.000003,0.000201,0.000019,

Public callable methods (listed separately): 2

                    name                                          signature
0          cross_predict  (x: 'NDVarArg | Sequence[NDVarArg]' = None, da...
1  partition_result_data                 (model: 'str' = None) -> 'Dataset'

## Inspect one attribute

Use `full=False` for a compact summary. Set `full=True` only when you intentionally want to print the underlying numeric array.

In [4]:
def show_attribute(name, full=False):
    if not hasattr(result, name):
        raise AttributeError(f'{type(result).__name__} has no attribute {name!r}')
    value = getattr(result, name)
    print(f'{name}: {type(value)}')
    display(pd.DataFrame([summarize_value(name, value, 'selected attribute')]))
    if full:
        if isinstance(value, NDVar):
            display(value.x)
        elif isinstance(value, np.ndarray):
            display(value)
        else:
            display(value)
    else:
        display(value)
    return value


r = show_attribute('r')
h = show_attribute('h')

r: <class 'eelbrain._data_obj.NDVar'>

,name,source,python_type,summary,dimensions,shape,dtype,finite,min,max,mean,error
0,r,selected attribute,eelbrain._data_obj.NDVar,<NDVar 'Correlation': 60 sensor>,"<Sensor n=60, name=None>","(60,)",float64,60/60,-0.044885,0.092227,0.03268,

h: <class 'eelbrain._data_obj.NDVar'>

,name,source,python_type,summary,dimensions,shape,dtype,finite,min,max,mean,error
0,h,selected attribute,eelbrain._data_obj.NDVar,"<NDVar 'gammatone-8': 60 sensor, 8 frequency, ...","<Sensor n=60, name=None>, Scalar('frequency', ...","(60, 8, 56)",float64,26880/26880,-0.010625,0.01575,-0.000013,

In [5]:
sensor_names = list(result.r.sensor.names)
checks = {
    'model_is_gammatone_8': result.x == MODEL,
    'tstart_matches': result.tstart == TRF_OPTIONS['tstart'],
    'tstop_matches': result.tstop == TRF_OPTIONS['tstop'],
    'error_is_l1': result.error == 'l1',
    'basis_is_50_ms': result.basis == 0.050,
    'five_partitions': result.splits.n_partitions == 5,
    'cross_validated': result.splits.n_test == 1,
    'sixty_eeg_sensors': result.r.shape == (60,),
    'eight_gammatone_bands': result.h.shape[1] == 8,
    'veog_excluded': 'VEOG' not in sensor_names,
    'aud_excluded': 'AUD' not in sensor_names,
    'r_is_finite': bool(np.isfinite(result.r.x).all()),
    'h_is_finite': bool(np.isfinite(result.h.x).all()),
}
check_table = pd.DataFrame(
    [{'check': name, 'passed': passed} for name, passed in checks.items()]
)
display(check_table)
print(f'All technical checks passed: {all(checks.values())}')
print(f'r range: {float(np.min(result.r.x)):.6f} to {float(np.max(result.r.x)):.6f}')
print(f'partition_results stored: {result.partition_results is not None}')

                    check  passed
0    model_is_gammatone_8    True
1          tstart_matches    True
2           tstop_matches    True
3             error_is_l1    True
4          basis_is_50_ms    True
5         five_partitions    True
6         cross_validated    True
7       sixty_eeg_sensors    True
8   eight_gammatone_bands    True
9           veog_excluded    True
10           aud_excluded    True
11            r_is_finite    True
12            h_is_finite    True

All technical checks passed: True
r range: -0.044885 to 0.092227
partition_results stored: False

## Inspect the cache manifest

The manifest is readable JSON. It records the cache key, estimator fingerprint, software versions, and input dependency fingerprints.

In [6]:
if MANIFEST_PATH.exists():
    manifest = json.loads(MANIFEST_PATH.read_text())
    print('Manifest top-level keys:', list(manifest))
    display(manifest)
else:
    manifest = None
    print('No manifest found next to the pickle.')

Manifest top-level keys: ['artifact_metadata', 'cache_policy', 'dependencies', 'derivative', 'derivative_version', 'fingerprint', 'key', 'resolve_options', 'resolve_state', 'schema_version', 'software']

{'artifact_metadata': {},
 'cache_policy': 'required',
 'dependencies': {'10~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '8e90ab88bcd94995ba78ed485950c371'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836260.8646214,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/10~gammatone-8.pickle',
     'size': 3922055}}},
  '11~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '0a469a50408d4ce7844f22d52f918d11'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836264.4850864,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/11~gammatone-8.pickle',
     'size': 3595719}}},
  '12~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '8ec358d61ca540b684957322d5cee97e'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836267.5699532,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/12~gammatone-8.pickle',
     'size': 3007751}}},
  '1~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '5c6130fce76b4c5395d2f10df7707114'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836223.8030534,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/1~gammatone-8.pickle',
     'size': 3683397}}},
  '2~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': 'e8b921f6d36f4bf794e10f0c9793184b'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836227.932263,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/2~gammatone-8.pickle',
     'size': 3894917}}},
  '3~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '00b188be17984072b2ed879816e318b3'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836232.1110992,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/3~gammatone-8.pickle',
     'size': 4049413}}},
  '4~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '4e8919771c6c443d8794e68d7849464a'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836236.8234227,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/4~gammatone-8.pickle',
     'size': 4480073}}},
  '5~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': 'dd7bb10e82504a00987765e078774a8c'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836241.221684,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/5~gammatone-8.pickle',
     'size': 4242249}}},
  '6~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': 'a695b06e96e84a509b4c7d7f07acb5f9'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836245.4018874,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/6~gammatone-8.pickle',
     'size': 4082565}}},
  '7~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '6471bc42536d4bb4af21a25fd5070822'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836249.415291,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/7~gammatone-8.pickle',
     'size': 4026181}}},
  '8~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': '4ff53a2647ab4ae49e8c68fd5b67a457'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836253.0801287,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/8~gammatone-8.pickle',
     'size': 3668677}}},
  '9~gammatone-8': {'dependencies': {},
   'fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'version': {'serial': 0, 'uid': 'dfc30dbdc4f240d295f9fcc8d7f34839'}},
   'kind': 'input',
   'name': 'predictor',
   'quick_fingerprint': {'config': {'resample': 'bin',
     'sampling': 'continuous',
     'type': 'AliceUTSPredictor'},
    'file': {'digest': None,
     'exists': True,
     'metadata': {},
     'mtime': 1779836256.7885823,
     'path': '/Users/yanyuwoo/Data/derivatives/predictors/9~gammatone-8.pickle',
     'size': 3663301}}},
  'response': {'dependencies': {'epoch-events': {'fingerprint': {'sample': [1832,
       30646,
       61094,
       92750,
       127772,
       160936,
       192850,
       224330,
       253011,
       281651,
       312306,
       340412],
      'tmax': 'duration'},
     'kind': 'input',
     'name': 'epoch-events'},
    'recording-epochs': {'dependencies': {'raw': {'dependencies': {'raw@raw': {'dependencies': {'raw-input-bads@raw': {'dependencies': {},
           'fingerprint': {'bads': []},
           'kind': 'input',
           'name': 'raw-input-bads@raw',
           'quick_fingerprint': {'digest': None,
            'exists': True,
            'metadata': {},
            'mtime': 1784595103.6552775,
            'path': 'sub-01/eeg/sub-01_task-alice_channels.tsv',
            'size': 3632}},
          'raw-input@raw': {'dependencies': {},
           'fingerprint': {'channels': {'digest': None,
             'exists': True,
             'metadata': {},
             'mtime': 1784595103.6552775,
             'path': 'sub-01/eeg/sub-01_task-alice_channels.tsv',
             'size': 3632},
            'pipe': {'adjacency': 'none',
             'kwargs': {},
             'montage': '<Sensor n=61, name=None>',
             'rename_channels': None,
             'sysname': None,
             'type': 'AudioAwareRawSource'},
            'raw': 'raw',
            'source': {'digest': None,
             'exists': True,
             'metadata': {},
             'mtime': 1782342444.165347,
             'path': 'sub-01/eeg/sub-01_task-alice_eeg.vhdr',
             'size': 1708}},
           'kind': 'input',
           'name': 'raw-input@raw'}},
         'fingerprint': {'pipe': {'adjacency': 'none',
           'kwargs': {},
           'montage': '<Sensor n=61, name=None>',
           'rename_channels': None,
           'sysname': None,
           'type': 'AudioAwareRawSource'}},
         'kind': 'input',
         'name': 'raw@raw'}},
       'fingerprint': {'pipe': {'h_freq': 20,
         'kwargs': {},
         'l_freq': 0.5,
         'n_jobs': 1,
         'source': 'raw',
         'type': 'RawFilter'},
        'raw': '0.5-20'},
       'kind': 'input',
       'name': 'raw@0.5-20'},
      'selected-events': {'fingerprint': {'sample': [1832,
         30646,
         61094,
         92750,
         127772,
         160936,
         192850,
         224330,
         253011,
         281651,
         312306,
         340412],
        'tmax': 'duration'},
       'kind': 'input',
       'name': 'selected-events'}},
     'fingerprint': {'epoch': {'baseline': False,
       'decim': None,
       'post_baseline_trigger_shift': None,
       'post_baseline_trigger_shift_max': None,
       'post_baseline_trigger_shift_min': None,
       'run': None,
       'samplingrate': 50,
       'sel': "segment != ''",
       'task': 'alice',
       'tmax': 'duration',
       'tmin': 0.0,
       'trigger_shift': 0.0,
       'type': 'PrimaryEpoch'},
      'reference': None},
     'kind': 'input',
     'name': 'recording-epochs'}},
   'fingerprint': {'epoch': {'baseline': False,
     'decim': None,
     'post_baseline_trigger_shift': None,
     'post_baseline_trigger_shift_max': None,
     'post_baseline_trigger_shift_min': None,
     'run': None,
     'samplingrate': 50,
     'sel': "segment != ''",
     'task': 'alice',
     'tmax': 'duration',
     'tmin': 0.0,
     'trigger_shift': 0.0,
     'type': 'PrimaryEpoch'},
    'options': {'baseline': False,
     'data': 'eeg',
     'decim': None,
     'interpolate_bads': True,
     'ndvar': True,
     'pad': 0,
     'reject': True,
     'reset_bads': True,
     'samplingrate': 50,
     'tmax': None,
     'tmin': None,
     'tstop': None}},
   'kind': 'input',
   'name': 'epochs'}},
 'derivative': 'trf',
 'derivative_version': 1,
 'fingerprint': {'estimator': {'backward': False,
   'basis': 0.05,
   'basis_window': 'hamming',
   'cv': True,
   'delta': 0.005,
   'error': 'l1',
   'mindelta': None,
   'partition_results': False,
   'partitions': -5,
   'scale_data': 'inplace',
   'selective_stopping': 1,
   'type': 'Boosting'}},
 'key': {'acquisition': '',
  'epoch': 'chapter-1',
  'epoch_rejection': '',
  'inv': '',
  'options': {'data': 'eeg',
   'decim': None,
   'estimator': 'boosting',
   'filter_x': 'continuous',
   'mask': None,
   'samplingrate': 50,
   'tstart': -0.1,
   'tstop': 1.0,
   'x': 'gammatone-8'},
  'raw': '0.5-20',
  'reference': '',
  'session': '',
  'subject': '01'},
 'resolve_options': {'data': 'eeg',
  'decim': None,
  'estimator': 'boosting',
  'filter_x': 'continuous',
  'mask': None,
  'samplingrate': 50,
  'tstart': -0.1,
  'tstop': 1.0,
  'x': 'gammatone-8'},
 'resolve_state': {'acquisition': '',
  'epoch': 'chapter-1',
  'epoch_rejection': '',
  'inv': '',
  'raw': '0.5-20',
  'reference': '',
  'session': '',
  'subject': '01'},
 'schema_version': 2,
 'software': {'eelbrain_cache_schema': '2', 'mne': '1.11.0'}}

## Optional summary export

Set `EXPORT_SUMMARIES = True` to write small CSV inventories. This exports summaries only, not the full `h` or `r` arrays.

In [7]:
EXPORT_SUMMARIES = False
OUTPUT_DIR = Path('/Users/yanyuwoo/Data/Alice Comprehension/qc/trf_pickle_inspection')

if EXPORT_SUMMARIES:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    public_path = OUTPUT_DIR / f'sub-{SUBJECT}_{MODEL}_public_attributes.csv'
    stored_path = OUTPUT_DIR / f'sub-{SUBJECT}_{MODEL}_stored_fields.csv'
    checks_path = OUTPUT_DIR / f'sub-{SUBJECT}_{MODEL}_technical_checks.csv'
    public_attributes.to_csv(public_path, index=False)
    stored_fields.to_csv(stored_path, index=False)
    check_table.to_csv(checks_path, index=False)
    print('Wrote:', public_path)
    print('Wrote:', stored_path)
    print('Wrote:', checks_path)
else:
    print('EXPORT_SUMMARIES is False; no files were written.')

EXPORT_SUMMARIES is False; no files were written.