# Unify BIDS Events Trial Type

This notebook standardizes Alice BIDS `events.tsv` files so stimulus markers use one consistent format.

Problem examples currently seen:

```text
Stimulus/1
Stimulus/S  1
Stimulus/S 12
```

Target format:

```text
trial_type = Stimulus/1 ... Stimulus/12
stimulus_id = 1 ... 12
raw_trial_type = original trial_type before normalization
```

Default mode is dry run. Set `DRY_RUN = False` only after reviewing the report.

In [1]:
from pathlib import Path
from datetime import datetime
import re
import shutil

import pandas as pd

BIDS_ROOT = Path('/Users/yanyuwoo/Data/bids')
ANALYSIS_ROOT = Path('/Users/yanyuwoo/Data/Alice Comprehension')
QC_DIR = ANALYSIS_ROOT / 'qc'
BACKUP_ROOT = ANALYSIS_ROOT / 'intermediate' / 'bids_events_backups'

# Keep True until the dry-run report looks right.
DRY_RUN = False

QC_DIR.mkdir(parents=True, exist_ok=True)
BACKUP_ROOT.mkdir(parents=True, exist_ok=True)

print(f'BIDS root: {BIDS_ROOT}')
print(f'DRY_RUN: {DRY_RUN}')

BIDS root: /Users/yanyuwoo/Data/bids
DRY_RUN: False

## Parser

The parser extracts the final stimulus number from both known formats and rejects anything outside `1..12`.

In [5]:
STIMULUS_RE = re.compile(r'^Stimulus/(?:S\s*)?(?P<stimulus_id>\d+)$')


def parse_stimulus_id(trial_type):
    if not isinstance(trial_type, str):
        return None
    match = STIMULUS_RE.match(trial_type.strip())
    if match is None:
        return None
    stimulus_id = int(match.group('stimulus_id'))
    if not 1 <= stimulus_id <= 12:
        return None
    return stimulus_id


assert parse_stimulus_id('Stimulus/1') == 1
assert parse_stimulus_id('Stimulus/12') == 12
assert parse_stimulus_id('Stimulus/S  1') == 1
assert parse_stimulus_id('Stimulus/S 12') == 12
print('Parser sanity check passed.')

Parser sanity check passed.

## Inspect all events files

In [6]:
events_paths = sorted(
    BIDS_ROOT.glob('sub-*/eeg/sub-*_task-alice_events.tsv'),
    key=lambda p: int(p.parts[-3].split('-')[1]),
)

rows = []
for path in events_paths:
    subject = path.parts[-3]
    df = pd.read_csv(path, sep='\t', encoding='utf-8-sig')
    parsed = df['trial_type'].map(parse_stimulus_id)
    rows.append({
        'subject': subject,
        'path': str(path),
        'n_rows': len(df),
        'n_stimulus_rows': int(parsed.notna().sum()),
        'stimulus_ids': ';'.join(map(str, sorted(parsed.dropna().astype(int).tolist()))),
        'missing_stimulus_ids': ';'.join(map(str, sorted(set(range(1, 13)) - set(parsed.dropna().astype(int).tolist())))),
        'original_trial_types': '; '.join(df['trial_type'].astype(str).tolist()),
        'needs_change': bool((df['trial_type'].astype(str) != parsed.map(lambda x: f'Stimulus/{int(x)}' if pd.notna(x) else None).astype(str)).any()),
        'unparsed_trial_types': '; '.join(df.loc[parsed.isna(), 'trial_type'].astype(str).tolist()),
    })

report = pd.DataFrame(rows)
report_path = QC_DIR / 'bids_events_trial_type_unify_dry_run.csv'
report.to_csv(report_path, index=False)
report[['subject', 'n_rows', 'n_stimulus_rows', 'missing_stimulus_ids', 'needs_change', 'unparsed_trial_types']]

,subject,n_rows,n_stimulus_rows,missing_stimulus_ids,needs_change,unparsed_trial_types
0,sub-01,12,12,,False,
1,sub-02,11,11,1,False,
2,sub-03,12,12,,False,
3,sub-04,12,12,,False,
4,sub-05,12,12,,False,
5,sub-06,12,12,,False,
6,sub-07,12,12,,False,
7,sub-08,12,12,,False,
8,sub-09,12,12,,False,
9,sub-10,12,12,,False,
10,sub-11,12,12,,False,
11,sub-12,12,12,,False,
12,sub-13,12,12,,False,
13,sub-14,12,12,,False,
14,sub-15,12,12,,False,
15,sub-16,12,12,,False,
16,sub-17,12,12,,False,
17,sub-18,12,12,,False,
18,sub-19,12,12,,False,
19,sub-20,12,12,,False,
20,sub-21,12,12,,False,
21,sub-22,12,12,,False,
22,sub-23,12,12,,False,
23,sub-24,11,11,1,False,
24,sub-25,12,12,,False,
25,sub-26,11,11,1,False,
26,sub-27,11,11,1,False,
27,sub-28,12,12,,False,
28,sub-29,11,11,1,False,
29,sub-30,11,11,1,False,
30,sub-31,12,12,,False,
31,sub-32,11,11,1,False,
32,sub-33,12,12,,False,
33,sub-34,11,11,1,False,
34,sub-35,11,11,1,False,
35,sub-36,11,11,1,False,
36,sub-37,12,12,,False,
37,sub-38,12,12,,False,
38,sub-39,12,12,,False,
39,sub-40,12,12,,False,
40,sub-41,12,12,,False,
41,sub-42,12,12,,False,
42,sub-43,12,12,,False,
43,sub-44,12,12,,False,
44,sub-45,12,12,,False,
45,sub-46,12,12,,False,
46,sub-47,12,12,,False,
47,sub-48,12,12,,False,
48,sub-49,11,11,1,False,

## Apply normalization

This cell writes only when `DRY_RUN = False`.

For each file:

1. Copy the original file into a timestamped backup directory.
2. Add `raw_trial_type` if absent.
3. Add/update `stimulus_id`.
4. Replace parseable stimulus rows in `trial_type` with `Stimulus/N`.
5. Save the updated `events.tsv`.

In [7]:
timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
backup_dir = BACKUP_ROOT / timestamp

apply_rows = []

for path in events_paths:
    subject = path.parts[-3]
    df = pd.read_csv(path, sep='\t', encoding='utf-8-sig')
    original_df = df.copy()

    parsed = df['trial_type'].map(parse_stimulus_id)
    parseable = parsed.notna()

    if 'raw_trial_type' not in df.columns:
        df['raw_trial_type'] = df['trial_type']

    df['stimulus_id'] = pd.NA
    df.loc[parseable, 'stimulus_id'] = parsed[parseable].astype(int)
    df.loc[parseable, 'trial_type'] = parsed[parseable].astype(int).map(lambda x: f'Stimulus/{x}')

    changed = not df.equals(original_df)

    if changed and not DRY_RUN:
        backup_dir.mkdir(parents=True, exist_ok=True)
        backup_path = backup_dir / path.name
        shutil.copy2(path, backup_path)
        df.to_csv(path, sep='\t', index=False)
    else:
        backup_path = None

    apply_rows.append({
        'subject': subject,
        'path': str(path),
        'changed': changed,
        'written': bool(changed and not DRY_RUN),
        'backup_path': str(backup_path) if backup_path else '',
        'n_stimulus_rows': int(parseable.sum()),
        'missing_stimulus_ids': ';'.join(map(str, sorted(set(range(1, 13)) - set(parsed.dropna().astype(int).tolist())))),
    })

apply_report = pd.DataFrame(apply_rows)
suffix = 'dry_run' if DRY_RUN else 'applied'
apply_report_path = QC_DIR / f'bids_events_trial_type_unify_{suffix}.csv'
apply_report.to_csv(apply_report_path, index=False)

print(f'Wrote report: {apply_report_path}')
if not DRY_RUN:
    print(f'Backups: {backup_dir}')

apply_report

Wrote report: /Users/yanyuwoo/Data/Alice Comprehension/qc/bids_events_trial_type_unify_applied.csv
Backups: /Users/yanyuwoo/Data/Alice Comprehension/intermediate/bids_events_backups/20260630-165654

,subject,path,changed,written,backup_path,n_stimulus_rows,missing_stimulus_ids
0,sub-01,/Users/yanyuwoo/Data/bids/sub-01/eeg/sub-01_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
1,sub-02,/Users/yanyuwoo/Data/bids/sub-02/eeg/sub-02_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
2,sub-03,/Users/yanyuwoo/Data/bids/sub-03/eeg/sub-03_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
3,sub-04,/Users/yanyuwoo/Data/bids/sub-04/eeg/sub-04_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
4,sub-05,/Users/yanyuwoo/Data/bids/sub-05/eeg/sub-05_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
5,sub-06,/Users/yanyuwoo/Data/bids/sub-06/eeg/sub-06_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
6,sub-07,/Users/yanyuwoo/Data/bids/sub-07/eeg/sub-07_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
7,sub-08,/Users/yanyuwoo/Data/bids/sub-08/eeg/sub-08_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
8,sub-09,/Users/yanyuwoo/Data/bids/sub-09/eeg/sub-09_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
9,sub-10,/Users/yanyuwoo/Data/bids/sub-10/eeg/sub-10_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
10,sub-11,/Users/yanyuwoo/Data/bids/sub-11/eeg/sub-11_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
11,sub-12,/Users/yanyuwoo/Data/bids/sub-12/eeg/sub-12_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
12,sub-13,/Users/yanyuwoo/Data/bids/sub-13/eeg/sub-13_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
13,sub-14,/Users/yanyuwoo/Data/bids/sub-14/eeg/sub-14_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
14,sub-15,/Users/yanyuwoo/Data/bids/sub-15/eeg/sub-15_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
15,sub-16,/Users/yanyuwoo/Data/bids/sub-16/eeg/sub-16_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
16,sub-17,/Users/yanyuwoo/Data/bids/sub-17/eeg/sub-17_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
17,sub-18,/Users/yanyuwoo/Data/bids/sub-18/eeg/sub-18_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
18,sub-19,/Users/yanyuwoo/Data/bids/sub-19/eeg/sub-19_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
19,sub-20,/Users/yanyuwoo/Data/bids/sub-20/eeg/sub-20_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
20,sub-21,/Users/yanyuwoo/Data/bids/sub-21/eeg/sub-21_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
21,sub-22,/Users/yanyuwoo/Data/bids/sub-22/eeg/sub-22_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
22,sub-23,/Users/yanyuwoo/Data/bids/sub-23/eeg/sub-23_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
23,sub-24,/Users/yanyuwoo/Data/bids/sub-24/eeg/sub-24_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
24,sub-25,/Users/yanyuwoo/Data/bids/sub-25/eeg/sub-25_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
25,sub-26,/Users/yanyuwoo/Data/bids/sub-26/eeg/sub-26_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
26,sub-27,/Users/yanyuwoo/Data/bids/sub-27/eeg/sub-27_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
27,sub-28,/Users/yanyuwoo/Data/bids/sub-28/eeg/sub-28_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
28,sub-29,/Users/yanyuwoo/Data/bids/sub-29/eeg/sub-29_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
29,sub-30,/Users/yanyuwoo/Data/bids/sub-30/eeg/sub-30_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
30,sub-31,/Users/yanyuwoo/Data/bids/sub-31/eeg/sub-31_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
31,sub-32,/Users/yanyuwoo/Data/bids/sub-32/eeg/sub-32_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
32,sub-33,/Users/yanyuwoo/Data/bids/sub-33/eeg/sub-33_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
33,sub-34,/Users/yanyuwoo/Data/bids/sub-34/eeg/sub-34_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
34,sub-35,/Users/yanyuwoo/Data/bids/sub-35/eeg/sub-35_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
35,sub-36,/Users/yanyuwoo/Data/bids/sub-36/eeg/sub-36_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1
36,sub-37,/Users/yanyuwoo/Data/bids/sub-37/eeg/sub-37_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
37,sub-38,/Users/yanyuwoo/Data/bids/sub-38/eeg/sub-38_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
38,sub-39,/Users/yanyuwoo/Data/bids/sub-39/eeg/sub-39_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
39,sub-40,/Users/yanyuwoo/Data/bids/sub-40/eeg/sub-40_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
40,sub-41,/Users/yanyuwoo/Data/bids/sub-41/eeg/sub-41_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
41,sub-42,/Users/yanyuwoo/Data/bids/sub-42/eeg/sub-42_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
42,sub-43,/Users/yanyuwoo/Data/bids/sub-43/eeg/sub-43_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
43,sub-44,/Users/yanyuwoo/Data/bids/sub-44/eeg/sub-44_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
44,sub-45,/Users/yanyuwoo/Data/bids/sub-45/eeg/sub-45_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
45,sub-46,/Users/yanyuwoo/Data/bids/sub-46/eeg/sub-46_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
46,sub-47,/Users/yanyuwoo/Data/bids/sub-47/eeg/sub-47_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
47,sub-48,/Users/yanyuwoo/Data/bids/sub-48/eeg/sub-48_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,12,
48,sub-49,/Users/yanyuwoo/Data/bids/sub-49/eeg/sub-49_ta...,True,True,/Users/yanyuwoo/Data/Alice Comprehension/inter...,11,1